package com.example.android.unscramble.ui.game
const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20

val allWordsList: List<String> =
    listOf("hewan",
        "auto",
        "anekdot",
        "alfabet",
        "semua",
        "luar biasa",
        "timbul",
        "balon",
        "keranjang",
        "bangku",
        "terbaik",
        "ulang tahun",
        "buku",
        "tas kantor",
        "kamera",
        "kamping",
        "lilin",
        "kucing",
        "kembang kol",
        "obrolan",
        "anak-anak",
        "kelas",
        "klasik",
        "ruang kelas",
        "kopi",
        "berwarna-warni",
        "kue kering",
        "kreatif",
        "pelayaran",
        "tari",
        "siang hari",
        "dinosaurus",
        "gagang pintu",
        "makan malam",
        "mimpi",
        "senja",
        "makan",
        "gajah",
        "zambrud",
        "seram",
        "listrik",
        "selesai",
        "bunga",
        "mengikuti",
        "rubah",
        "bingkai",
        "gratis",
        "sering",
        "corong",
        "hijau",
        "gitar",
        "kebutuhan",
        "kaca",
        "hebat",
        "cekikikan",
        "potong rambut",
        "setengah",
        "buatan rumah",
        "terjadi",
        "madu",
        "cepat",
        "seratus",
        "es",
        "igloo",
        "menginvestasikan",
        "mengundang",
        "logo",
        "memperkenalkan",
        "lelucon",
        "gembira",
        "jurnal",
        "lompat",
        "bergabung",
        "kangguru",
        "keyboard",
        "dapur",
        "koala",
        "macam",
        "kaledoskop",
        "pemandangan",
        "terlambat",
        "tertawa",
        "belajar",
        "lemon",
        "surat",
        "bakung",
        "majalah",
        "kelautan",
        "marshmallow",
        "labirin",
        "bermeditasi",
        "melodi",
        "menit",
        "monumen",
        "bulan",
        "motor",
        "gunung",
        "musik",
        "utara",
        "hidung",
        "malam",
        "nama",
        "tidak pernah",
        "bernegoisasi",
        "nomor",
        "berlawanan",
        "gurita",
        "ek",
        "pesanan",
        "buka",
        "kutub",
        "mengemas",
        "lukisan",
        "orang",
        "piknik",
        "bantal",
        "pizza",
        "podcast",
        "presentasi",
        "anak anjing",
        "teka-teki",
        "resep",
        "menerbitkan",
        "restaurant",
        "berputar",
        "memutar ulang",
        "ruangan",
        "lari",
        "rahasia",
        "benih",
        "kapal",
        "kemeja",
        "sebaiknya",
        "kecil",
        "kapal angkasa",
        "astronomi",
        "kemampuan",
        "jalan",
        "gaya",
        "matahari terbit",
        "taksi",
        "rapi",
        "pengatur waktu",
        "bersama",
        "gigi",
        "turis",
        "travel",
        "truk",
        "di bawah",
        "berguna",
        "unicorn",
        "unik",
        "mengangkat",
        "seragam",
        "vas",
        "biola",
        "pengunjung",
        "penglihatan",
        "volume",
        "melihat",
        "anjing laut",
        "berkelana",
        "dunia",
        "musim dingin",
        "baik",
        "angin puyuh",
        "x-ray",
        "xylophone",
        "yoga",
        "yogurt",
        "yoyo",
        "kamu",
        "tahun",
        "enak",
        "zebra",
        "zigzag",
        "zoologi",
        "daerah",
        "semangat")